In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
cd drive/MyDrive

/content/drive/MyDrive


In [ ]:
!pip install transformers
!pip install sentencepiece
!pip install bertopic

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 41.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 27.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 95.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 70.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 43.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.4/143.4 kB 11.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 85.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 kB 9.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 5.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 42.4 MB/s

In [ ]:
!pip install bertopic[visualization]

In [ ]:
!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'

  Cloning https://github.com/SKTBrain/KoBERT.git to /tmp/pip-install-iibids70/kobert-tokenizer_6193482e4dbb4c109ab2a9fecb1fe8b3
  Running command git clone --filter=blob:none --quiet https://github.com/SKTBrain/KoBERT.git /tmp/pip-install-iibids70/kobert-tokenizer_6193482e4dbb4c109ab2a9fecb1fe8b3
  Resolved https://github.com/SKTBrain/KoBERT.git to commit 47a69af87928fc24e20f571fe10c3cc9dd9af9a3
  Preparing metadata (setup.py) ... done
  Created wheel for kobert_tokenizer: filename=kobert_tokenizer-0.1-py3-none-any.whl size=4632 sha256=6649c271fbd8c12237e5523392428a6d174cbaaaa7c5347c5ea1968ae8c1999e
  Stored in directory: /tmp/pip-ephem-wheel-cache-429wkt3k/wheels/e9/1a/3f/a864970e8a169c176befa3c4a1e07aa612f69195907a4045fe
Successfully built kobert_tokenizer


In [ ]:
from tqdm import tqdm
from sklearn.feature_extraction.text import CountVectorizer
from bertopic import BERTopic
import os
import json

In [ ]:
import re

cond = re.compile('[가-힣]+')

def get_data(gallery):
  result = []
  for name in os.listdir(path='/content/drive/MyDrive/jolnon/' + gallery):
    with open('/content/drive/MyDrive/jolnon/' + gallery + '/' + name, 'r', encoding='utf-8') as f:
      data = json.load(f)
      valid = []
      for d in data['content'].split('\n'):
        res = []
        for word in d.split(' '):
          if cond.match(word) != None:
            res.append(word)
        d = ' '.join(res)
        if d and not d.replace(' ', '').isdecimal():
          valid.append(d)
      result.append('\n'.join([data['title']] + valid))
  return result

In [ ]:
import random
random.seed(42)
galleries = ['ktwiz','hanwhaeagles_new','skwyverns_new1','ncdinos','samsunglions_new','doosanbears_new1','giants_new2','sh_new','lgtwins_new','tigers_new']
dataset = []
for e in galleries:
  dataset.append([get_data(e)])
cocktail = []
for data in dataset:
  for sen in data:
    cocktail+=sen
cocktail[:5]

['박세진 올스타전 참가 ㅋㅋㅋㅋ',
 '저거 박세진 아님?????',
 '사실 박세진이 오른손으로 던진거라면?',
 '아시발 그만쳐 개색기들아',
 '아니 뭐 배팅볼이냐 ㅋㅋㅋ 다쳐맞노 ㅋㅋㅋㅋㅋㅋㅋ']

In [ ]:
print(cocktail[0])

박세진 올스타전 참가 ㅋㅋㅋㅋ


In [ ]:
def remove_words(sentence, word):
    return ' '.join([w for w in sentence.split(' ') if word not in w.lower()])
stopwords = ['ㅋㅋ', 'ex', '나는', 'on', '이미지', '순서', '오늘', '일단', 'and', '이야', '그리고', '내일', '그냥', '000', '조금', '살짝', 'ㅇㅇ', 'ㅈㄱㄴ', '있음', '이거', '내가', '칵하하하', '칵하핫', '근데', '지듣노', 'youtube ', '야스중', '우흥', '한다', 'ㅎㅎ', 'ㅠㅠ', '로오오오오오옹', '하고', '아침', '것도', '추천', '혹시', '새낀데', '같다']

In [ ]:
for i in range(len(cocktail)):
  for j in range(len(stopwords)):
    cocktail[i] = remove_words(cocktail[i],stopwords[j])

In [ ]:
bertopic_model = BERTopic(language='multilingual',
                          nr_topics=100,
                          top_n_words=10,
                          calculate_probabilities=True)

In [ ]:
topics, probs = bertopic_model.fit_transform(cocktail)

In [ ]:
bertopic_model.visualize_topics()

In [ ]:
bertopic_model.visualize_distribution(probs[0])

In [ ]:
from sklearn.cluster import KMeans

n_clusters = len(dataset)
kmeans = KMeans(n_clusters=n_clusters, random_state=0)
kmeans.fit(probs)
labels = kmeans.labels_


In [ ]:
real_labels = []
for i in range(len(dataset)):
  real_labels += [i] * len(dataset[i][0])
from sklearn.metrics import confusion_matrix
print(len(real_labels))
print(confusion_matrix(real_labels, labels))


24792
[[719 139  42   4 534  55  10 756   1  13]
 [919 123  11  14 673 112  27 601   1   3]
 [895 149  43   8 607  73  14 755   2  10]
 [775 194  84  11 648  75  13 757   7  26]
 [810 119  10  27 603 162  23 584   9   1]
 [803 138  74   9 632  66  12 794   5  20]
 [839 102   3  13 562  83  12 471   1   5]
 [755 146  56  13 656  71  15 744   3  30]
 [957 222  79  16 653  71  10 974   5  21]
 [730 184  54  15 533  66  15 783   2  18]]


In [ ]:
import numpy as np
from scipy.optimize import linear_sum_assignment
from sklearn.metrics import confusion_matrix

def calc_purity(y_true, y_pred):
    cm = confusion_matrix(y_true, y_pred)
    _, col_ind = linear_sum_assignment(cm, maximize=True)
    reordered_cm = cm[:, col_ind]
    purity = np.sum(np.max(reordered_cm, axis=0)) / np.sum(reordered_cm)
    return purity, reordered_cm

purity, reordered_cm = calc_purity(real_labels, labels)

print("Purity: ", purity)
print("Reordered Confusion Matrix: \n", reordered_cm)

Purity:  0.1276621490803485
Reordered Confusion Matrix: 
 [[  1 534 719 139  55  42   4  13 756  10]
 [  1 673 919 123 112  11  14   3 601  27]
 [  2 607 895 149  73  43   8  10 755  14]
 [  7 648 775 194  75  84  11  26 757  13]
 [  9 603 810 119 162  10  27   1 584  23]
 [  5 632 803 138  66  74   9  20 794  12]
 [  1 562 839 102  83   3  13   5 471  12]
 [  3 656 755 146  71  56  13  30 744  15]
 [  5 653 957 222  71  79  16  21 974  10]
 [  2 533 730 184  66  54  15  18 783  15]]


In [ ]:
def show_cluster_examples(data, labels, n_clusters, examples_per_cluster=3):
    for cluster in range(n_clusters):
        print(f"Cluster {cluster + 1}:")

        cluster_indices = np.where(labels.astype(int) == cluster)[0]

        # Get examples from the cluster
        cluster_examples = [data[idx] for idx in cluster_indices]

        # Show example items
        for example in cluster_examples[:examples_per_cluster]:
            print(example)
        print()

n_clusters = len(dataset)
kmeans = KMeans(n_clusters=n_clusters, random_state=0)
kmeans.fit(probs)
labels = kmeans.labels_

# Show cluster examples
show_cluster_examples(cocktail, labels, n_clusters)


Cluster 1:
아니 뭐 배팅볼이냐 다쳐맞노
세웅이는 어디가고 세진이가...?
공지) 이새끼 형이 맞습니다
이새끼가 오른손으로 던지는게 아닌 이상 답이 없습니다.

Cluster 2:
전준우 판박이노
벌레새끼들아 ㅅㅂ 그만좀해
영현이 타석 한번 보고싶지 않냐

Cluster 3:




Cluster 4:
역대급 개노잼
진짜 올해만큼 재미없는적도 처음이네 개노잼 차라리 비와서 취소되는게 나았을지도..
너무 롯데 노래만부른다
양의지 노래부르고싶었는데 롯데부르느라 교체
병호형도 다롯데노래
킸장 부르고싶은데 또 부산항..
슬프노
☆이스타 코구비하관련 해축갤13시30분 회식☆

Cluster 5:
사실 박세진이 오른손으로 던진거라면?
세진이 언제 감추로 형 유니폼입고왔네
안경도썼네
홍크라테스 쓰리런.GIF

Cluster 6:
김주원거르고누구뽑음?
북괴년 응원댄스 웃기노
당장 소형준 김민수 배제성 데려와서 위즈파 재결성

Cluster 7:
렐라상수 그 짤.jpg
현역 투수 통산 세이브 순위... .jpg
현역 야수 통산 병살타 순위... .jpg

Cluster 8:
박세진 올스타전 참가
저거 박세진 아님?????
아시발 그만쳐 개색기들아

Cluster 9:
칩) 느그 프런트가 좆쥐팬이라 했다는거 실화냐?
김현준은 어리기나하지 프런트는
홍크라테스가 퍼포먼스 받았으먄 그나마 인정인데 리신보다도 노잼인 김민석이 받네
김민석은 뭐했음 못 봐서 그런데 뷰지는 퍼포먼스 안 봐도 좋았을 거 알고 소크도 트렘펫불고 나오더니 홈머까고 다음 타석에 건 봤는데 김민석은 뭐함?

Cluster 10:
ㅅㅂ
우익수
오

